config/routes.rb
Rails.application.routes.draw do
  unauthenticated :user do
    devise_scope :user do
      root to: 'devise/sessions#new'
    end
  end

  authenticated :user do
    root to: 'comments#index'
  end

  resources :comments, only: [:new, :create]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable,
  # :omniauthable, :registerable, :recoverable, :rememberable
  devise :database_authenticatable, :validatable

  has_many :comments, dependent: :destroy

  def self.comments_desc
    left_joins(:comments).includes(:comments).distinct.order("comments.id desc")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.comments_desc
  end

  def new
    @comment = current_user.comments.build
  end

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to root_url, notice: (I18n.t 'notice.create_comment')
    else
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.slim
.row
  .mx-auto
    - @users.each do |user|
      - if user.comments.last
        span.fa.fa-user-o = " #{user.display_name}"
        .balloon-left
          p.comment-txt.p-2
            = user.comments.last.content
        br

app/views/comments/new.html.slim
.row
  .mx-auto
    .card.mt-5.comment-new
      .card-header.px-5.pt-3
        h4.text-center
          .fa.fa-commenting-o = " つぶやく"
      .card-body.px-5
        = form_with(model: @comment, local: true) do |f|
          = render 'shared/error_messages', error_object: @comment
          .form-group
            = f.text_area :content, class: "form-control", rows: "3"
          .form-group
            = f.submit "投稿", class: "btn btn-outline-secondary btn-block mt-4"

app/views/layouts/_header.html.slim
header.sticky-top.border
  nav.navbar.navbar-expand-lg.navbar-light.bg-white
    = link_to "ひとこと", root_url, class: "navbar-brand", id: "logo"
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替"]
      span.navbar-toggler-icon
    #Navber.collapse.navbar-collapse
      - if user_signed_in?
        ul.navbar-nav.mr-auto
          li.nav-item.active
            = link_to " つぶやく", new_comment_path,
              class: "nav-link text-dark header-item fa fa-commenting-o"
          li.nav-item.active
            = link_to " ログアウト", destroy_user_session_path,
              class: "nav-link text-dark header-item fa fa-sign-out",
              method: :delete
            span.sr-only
              | (現位置)
        .nav-link.text-dark.header-item.fa.fa-user-o
          = " #{current_user.display_name}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title = "ひとこと"
    = favicon_link_tag('favicon.ico')
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .main.container
      - flash.each do |message_type, message|
        - message_type = "secondary" if message_type == "notice"
        - message_type = "danger"    if message_type == "alert"
        div class=("alert alert-#{message_type}") = message
      = yield

app/views/shared/_error_messages.html.slim
- if error_object.errors.any?
  #error_explanation
    ul
      - error_object.errors.full_messages.each do |msg|
        li
          = msg